# version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=kS1p_UhHHit_dOmJw1JO1e6PiQLV0xlF7bq5O4U65bw
      - AUTHORIZED_IP=172.19.0.1
    networks:
      - lab-network

  microservice:
    build: ./microservice1
    expose:
      - "5001"
    networks:
      - lab-network

  database:
    build: ./database
    expose:
      - "5002"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge