services:
  api:
    build: ./api
    ports:
      - "5000:5000"
  database:
    build: ./database

  microservice:
    build: ./microservice
    depends_on:
      - database

networks:
  default:
    driver: bridge
