# Use an official Python image from Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the local directory contents into the container at /app
COPY . /app

RUN pip install flask
RUN pip install pyjwt

# Run the Python script
CMD ["python", "database.py"]