version: '3.8'

services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "8000:8000"

  cache:
    build: ./cache
    ports:
      - "5004:5004"

  api_gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"

  microservice:
    build: ./microservice
    ports:
      - "5001:5001"

  worker:
    build: ./worker
    ports:
      - "5005:5005"

  database:
    build: ./database
    ports:
      - "5002:5002"