# Use an official Python image from Docker Hub
FROM python:3.13-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the local directory contents into the container at /app
COPY . /app

RUN pip install asyncio
RUN pip install websockets

# Run the Python script
CMD ["python", "broker.py"]