services:
  api_gateway:    
    image: project_afact_ag_img
    build:     
      context: .
      dockerfile: /efact_ag/Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    networks:
      - secure_net
    container_name: project_afact_ag

  auth_service:
    image: project_auth_be_img
    build: 
      context: .  
      dockerfile:  /auth_be/Dockerfile      
    env_file: .env
    networks:
      - secure_net
    container_name: project_auth_be

networks:
  secure_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
