services:

  api_gateway:
    build: ./api_gateway  # Construir desde el subdirectorio
    container_name: api_gateway  # Nombre fijo del contenedor
    ports:
      - "${API_GATEWAY_PORT}:5000"  # Mapeo dinámico usando variable de entorno
    env_file:
      - .env  # Archivo externo con variables de entorno
    networks:
      - internal_net  # Conectado a la red interna
      - public_net  # Conectado a la red pública

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "${ORDER_SERVICE_PORT}:5001"
    env_file:
      - .env
    networks:
      - internal_net

  inventory_service:
    build: ./inventory_service
    container_name: inventory_service
    ports:
      - "${INVENTORY_SERVICE_PORT}:5002"
    env_file:
      - .env
    networks:
      - internal_net

  reporting_service:
    build: ./reporting_service
    container_name: reporting_service
    ports:
      - "${REPORTING_SERVICE_PORT}:5003"
    env_file:
      - .env
    networks:
      - internal_net

# Redes definidas
networks:
  private_net: # Red interna para comunicación entre servicios
    driver: bridge
    internal: true  # Esto evita exposición a la red externa
  public_net:
    driver: bridge  # Red pública para acceso externo
