version: '3'
services:
  load_balancer:
    build: ./load_balancer
    ports:
      - '8000:8000'
  api_gateway_1:
    build: ./api_gateway
    ports:
      - '5000:5000'
  api_gateway_2:
    build: ./api_gateway
    ports:
      - '5003:5000'
  cache:
    build: ./cache
    ports:
      - '5004:5004'
  database:
    build: ./database
    ports:
      - '5002:5002'
  microservice:
    build: ./microservice
    ports:
      - '5001:5001'
  worker:
    build: ./worker
    ports:
      - '5005:5005'